# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 16:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('hidden', models.BooleanField(default=False)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('view_name', models.CharField(max_length=100)),
            ],
        ),
    ]
