# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 13:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PyplotVisualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('hidden', models.BooleanField(default=False)),
                ('icon', models.ImageField(default='visualizer/static/visualizer/img/default-img.jpg', upload_to='visualizer/static/visualizer/img/')),
                ('type', models.CharField(default='', max_length=512)),
                ('order', models.IntegerField(default=999)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('view_name', models.CharField(max_length=100)),
            ],
        ),
    ]
