# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_visualization_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='icon',
            field=models.ImageField(default='visualizer/img/default-img.jpg', upload_to='visualizer/img/'),
        ),
    ]
