# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_auto_20171115_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='icon',
            field=models.ImageField(default='/visualizer/static/visualizer/img/default-img.jpg', upload_to='/visualizer/static/visualizer/img/'),
        ),
    ]
