# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_auto_20171220_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='icon',
            field=models.ImageField(default='visualizer/static/visualizer/img/default-img.jpg', upload_to='visualizer/static/visualizer/img/'),
        ),
    ]
