# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0005_auto_20180312_0952'),
        ('visualizer', '0005_auto_20180202_1226'),
    ]

    operations = [
    ]
