# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 20:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0006_merge_20180509_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
