# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0006_merge_20180509_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='type',
            field=models.CharField(default='', max_length=512),
        ),
    ]
