# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0007_auto_20180522_2315'),
        ('visualizer', '0007_visualization_type'),
    ]

    operations = [
    ]
