# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0007_auto_20180522_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='type',
            field=models.CharField(default='', max_length=512),
        ),
    ]
