# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0010_pyplotvisualisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='data_source',
            field=models.CharField(default='query', max_length=512),
        ),
    ]
