# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 13:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDataframes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('private', models.BooleanField(default=False)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('notebook_id', models.CharField(max_length=100)),
                ('arguments_paragraph_id', models.CharField(max_length=100, null=True)),
                ('queries', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('output_html', models.TextField(null=True)),
                ('output_css', models.TextField(null=True)),
                ('output_js', models.TextField(null=True)),
                ('through_livy', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('price', models.CharField(default='free', max_length=50)),
                ('imageurl', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('valid', models.BooleanField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_builder.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='open', max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 2, 16, 0, 44, 603000))),
                ('response_date', models.DateTimeField(null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='service_builder.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('notebook_id', models.CharField(max_length=100, null=True)),
                ('livy_session', models.IntegerField(null=True)),
                ('status', models.CharField(default='', max_length=100, null=True)),
                ('output_page', models.CharField(default='', max_length=100, null=True)),
                ('dataframe_visualizations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_builder.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='access_list',
            field=models.ManyToManyField(through='service_builder.ServiceAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
