# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publised',
            field=models.BooleanField(default=False),
        ),
    ]
