# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0003_servicetemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='publised',
            new_name='published',
        ),
    ]
