# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 10:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0004_auto_20180402_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='service',
            name='output_css',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='output_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='output_js',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='queries',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
