# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0005_auto_20180402_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arguments_paragraph_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
