# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0006_service_arguments_paragraph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arguments_paragraph_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
