# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 21:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0007_auto_20180507_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='queries',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
