# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0009_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='imageurl',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
