# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 08:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0011_auto_20180513_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='queries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
