# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0014_serviceexecution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceExecution',
            new_name='ServiceInstance',
        ),
    ]
