# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_builder', '0016_service_through_livy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceaccess',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_builder.Service'),
        ),
        migrations.AddField(
            model_name='serviceaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='access_list',
            field=models.ManyToManyField(through='service_builder.ServiceAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
