# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0017_auto_20180717_1404'),
        ('service_builder', '0017_auto_20180914_2352'),
    ]

    operations = [
    ]
