# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0018_merge_20181009_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_user',
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
