# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0019_auto_20181009_1241'),
        ('service_builder', '0018_merge_20181023_1401'),
    ]

    operations = [
    ]
