# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 16:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_builder', '0020_merge_20181120_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='open', max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 2, 21, 18, 6, 48, 658000))),
                ('response_date', models.DateTimeField(null=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='service',
        #     name='service_user',
        # ),
        # migrations.AlterField(
        #     model_name='service',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddField(
            model_name='serviceaccessrequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='service_builder.Service'),
        ),
        migrations.AddField(
            model_name='serviceaccessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
