# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 10:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0021_auto_20190221_1806'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='service',
        #     name='service_user',
        # ),
        # migrations.AlterField(
        #     model_name='service',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='serviceaccessrequest',
        #     name='creation_date',
        #     field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 12, 58, 43, 807000)),
        # ),
    ]
