# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0022_auto_20190327_1258'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='serviceaccessrequest',
        #     name='creation_date',
        #     field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 17, 6, 32, 636000)),
        # ),
    ]
