# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 13:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_builder', '0023_auto_20190527_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDataframes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_user',
        ),
        migrations.AddField(
            model_name='service',
            name='can_be_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 16, 27, 30, 111000)),
        ),
    ]
