# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userreq', models.CharField(max_length=20)),
                ('userpost', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.TextField(max_length=500)),
                ('service_description', models.TextField(max_length=500)),
                ('service_type', models.CharField(choices=[('CD', 'Custom Data'), ('RP', 'Report')], default='CD', max_length=2)),
                ('deadline', models.DateField(default=datetime.date(2018, 2, 26))),
                ('budget', models.IntegerField()),
                ('file', models.FileField(upload_to='images/')),
                ('category_type', models.CharField(choices=[('C1', 'Category 1'), ('C2', 'Category 2'), ('C3', 'Category 3')], default='C1', max_length=2)),
                ('provider', models.CharField(choices=[('NT', 'NTUA'), ('EX', 'EXHILE'), ('AL', 'Every BDO Provider')], default='NT', max_length=2)),
                ('email_notification', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='requestid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestservice.UserRequests'),
        ),
        migrations.AddField(
            model_name='messagenotify',
            name='messageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestservice.Messages'),
        ),
    ]
