# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 23:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestservice', '0002_auto_20180403_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2018, 4, 15)),
        ),
    ]
