# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestservice', '0004_auto_20180423_1727'),
        ('requestservice', '0004_auto_20180506_2318'),
    ]

    operations = [
    ]
