# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestservice', '0005_merge_20180509_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2018, 5, 11)),
        ),
    ]
