# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 09:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('FINISHED', 'Finished'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('service_id', models.IntegerField()),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
