# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20170823_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinstance',
            name='base_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo_main_app.Service'),
        ),
    ]
