# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 13:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wave_Energy_Converters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_uri', models.CharField(max_length=200)),
                ('sample_rows', django.contrib.postgres.fields.jsonb.JSONField()),
                ('min_height', models.FloatField(blank=True, default=None, null=True)),
                ('max_height', models.FloatField(blank=True, default=None, null=True)),
                ('min_energy_period', models.FloatField(blank=True, default=None, null=True)),
                ('max_energy_period', models.FloatField(blank=True, default=None, null=True)),
                ('nominal_power', models.FloatField(blank=True, default=None, null=True)),
                ('height_step', models.FloatField(blank=True, default=None, null=True)),
                ('period_step', models.FloatField(blank=True, default=None, null=True)),
                ('owner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
