# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_energy_pilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave_energy_converters',
            name='height_step',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='max_energy_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='max_height',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='min_energy_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='min_height',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='nominal_power',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='period_step',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
