# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wave_energy_pilot', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='height_step',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='max_energy_period',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='max_height',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='min_energy_period',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='min_height',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='nominal_power',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='owner_id',
        #     field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='wave_energy_converters',
        #     name='period_step',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
    ]
