# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_energy_pilot', '0002_auto_20190329_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wave_energy_converters',
            name='period_step',
        ),
        migrations.AddField(
            model_name='wave_energy_converters',
            name='owner_id',
            field=models.IntegerField(default=None),
        ),
    ]
