# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_energy_pilot', '0003_auto_20190329_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave_energy_converters',
            name='period_step',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
