# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wave_energy_pilot', '0005_remove_wave_energy_converters_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave_energy_converters',
            name='owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
