# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.TextField(default='Temporary query'),
        ),
    ]
