# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 10:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_designer', '0002_auto_20170623_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='design',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.TextField(default='Untitled query'),
        ),
    ]
