# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_designer', '0004_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
