# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_designer', '0005_auto_20180202_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='generated_by',
            field=models.CharField(choices=[('CUSTOM', 'Custom query'), ('QDv1', 'Query Designer (old)'), ('QDv2', 'Query Designer (new)')], default='v1', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='v2_fields',
            field=models.TextField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='v2_filters',
            field=models.TextField(blank=True, default=None, editable=False, null=True),
        ),
    ]
