# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_designer', '0007_auto_20180323_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempquery',
            name='original',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='query_designer.Query'),
            preserve_default=False,
        ),
    ]
