# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_designer', '0010_dataset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset_user',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dataset_User',
        ),
    ]
