# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='data_column_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='data_table_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
