# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20170513_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='axis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
