# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20170513_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type_of_analysis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
