# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20170513_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=50, default=None, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=50, default=None, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=50, default=None, max_digits=100, null=True),
        ),
    ]
