# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_auto_20170515_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='unit',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='variable',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.CharField(max_length=256),
        ),
    ]
