# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(_, __):
    from aggregator.models import Variable
    from django.db import connection
    for v in Variable.objects.all():
        v.update_distribution(connection.cursor())


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_auto_20170621_1321'),
    ]

    operations = [
        # migrations.RunPython(forwards)
    ]
