# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0012_auto_20180403_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='stored_at',
            field=models.CharField(choices=[(b'LOCAL_POSTGRES', b'Local PostgreSQL instance'), (b'UBITECH_POSTGRES', b"UBITECH's PostgreSQL instance at http://212.101.173.21"), (b'UBITECH_SOLR', b'Solr instance at http://212.101.173.50:8983')], default=b'LOCAL_POSTGRES', max_length=32),
        ),
    ]
