# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0014_min_max_dimension_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinOfDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100)),
                ('dataset_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='aggregator.Dataset')),
                ('dataset_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='aggregator.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='joined_with_dataset',
            field=models.ManyToManyField(related_name='joined_to', through='aggregator.JoinOfDatasets', to='aggregator.Dataset'),
        ),
    ]
