# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0016_min_max_dimension_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='description',
        ),
    ]
