# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0015_dataset_dataset_user'),
        ('aggregator', '0016_min_max_dimension_column'),
    ]

    operations = [
    ]
