# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_auto_20181026_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
