# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_merge_20181009_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_user',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='state',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='description',
        ),
    ]
