# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0019_dataset_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
