# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0018_auto_20181009_1241'),
        ('aggregator', '0019_auto_20180926_1243'),
    ]

    operations = [
    ]
