# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 10:21
from __future__ import unicode_literals

from django.db import connections
from django.db import migrations


def forwards(_, __):
    fill_organization_table()


def fill_organization_table():
    insert_default_query = build_insert_default_query()
    #query = build_insert_query()
    execute_insert_query(insert_default_query)
    #execute_insert_query(query)


def build_insert_query():
    return """INSERT INTO aggregator_organization (title,description) 
              SELECT DISTINCT source,''
              FROM aggregator_dataset 
              WHERE source != ''
              """


def build_insert_default_query():
    return """INSERT INTO aggregator_organization (ID, title,description) 
              SELECT 1,'',''
              WHERE NOT EXISTS 
                (SELECT 1 
                FROM aggregator_organization 
                WHERE id=1)"""


def execute_insert_query(query):
    cursor = connections['default'].cursor()
    cursor.execute(query)


class Migration(migrations.Migration):
    dependencies = [
        ('aggregator', '0020_organization'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
