# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_merge_20181023_1401'),
        ('aggregator', '0020_auto_20181106_1624'),
        ('aggregator', '0023_update_organization_for_dataset'),
    ]

    operations = [
    ]
