# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 15:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0024_merge_20181120_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='license',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='dataset',
            name='observation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='publisher',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='spatiaNorth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='spatialEast',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='spatialSouth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='spatialWest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='temporalCoverageBegin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='temporalCoverageEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='aggregator.Organization'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='stored_at',
            field=models.CharField(choices=[(b'LOCAL_POSTGRES', b'Local PostgreSQL instance'), (b'UBITECH_POSTGRES', b"UBITECH's PostgreSQL instance at http://212.101.173.21"), (b'UBITECH_PRESTO', b"UBITECH's PRESTO instance"), (b'UBITECH_SOLR', b'Solr instance at http://212.101.173.50:8983')], default=b'LOCAL_POSTGRES', max_length=32),
        ),
    ]
