# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 16:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0025_auto_20181122_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='cell_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
