# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0026_auto_20181122_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='spatiaNorth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='spatialEast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='spatialSouth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='spatialWest',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
