# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 12:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0027_auto_20181122_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='image_uri',
            field=models.TextField(default=b'/static/img/logo.png'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='number_of_rows',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='sample_rows',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='size_in_gb',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='update_frequency',
            field=models.CharField(default=b'static file', max_length=200),
        ),
    ]
