# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0028_auto_20181127_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='number_of_rows',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
