# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0018_auto_20181026_1700'),
        ('aggregator', '0029_auto_20181127_1511'),
    ]

    operations = [
    ]
