# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0031_dataset_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='dataType',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='original_column_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='sameAs',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='dataType',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='original_column_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='sameAs',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
