# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0031_dataset_order'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='dataset',
        #     old_name='spatiaNorth',
        #     new_name='spatialNorth',
        # ),
        # migrations.RemoveField(
        #     model_name='dimension',
        #     name='description',
        # ),
        # migrations.RemoveField(
        #     model_name='variable',
        #     name='description',
        # ),
    ]
