# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('aggregator', '0032_auto_20190118_1720'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='dataset',
        #     old_name='spatiaNorth',
        #     new_name='spatialNorth',
        # ),
    ]
