# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0033_auto_20190118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='update_frequency',
            field=models.CharField(default=b'-', max_length=200),
        ),
    ]
