# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0032_auto_20190130_1208'),
        ('aggregator', '0034_auto_20190121_1355'),
    ]

    operations = [
    ]
