# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 16:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0035_merge_20190218_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'open', b'open'), (b'accepted', b'accepted'), (b'rejected', b'rejected')], default=b'open', max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 2, 21, 18, 6, 48, 281000))),
                ('response_date', models.DateTimeField(null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='aggregator.Dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.AddField(
        #     model_name='dimension',
        #     name='description',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='variable',
        #     name='description',
        #     field=models.TextField(null=True),
        # ),
    ]
