# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0036_auto_20190221_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='hascoverage_img',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='dimension',
        #     name='description',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='variable',
        #     name='description',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='datasetaccessrequest',
        #     name='creation_date',
        #     field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 43, 58, 964000)),
        # ),
    ]
