# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0037_auto_20190225_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='observation',
            new_name='observations',
        ),
        # migrations.AddField(
        #     model_name='dimension',
        #     name='description',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='variable',
        #     name='description',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='datasetaccessrequest',
        #     name='creation_date',
        #     field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 53, 27, 811000)),
        # ),
    ]
