# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 12:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0038_auto_20190619_1303'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DatasetAccessRequest',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('status', models.CharField(choices=[(b'open', b'open'), (b'accepted', b'accepted'), (b'rejected', b'rejected')], default=b'open', max_length=20)),
        #         ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 2, 15, 25, 33, 311000))),
        #         ('response_date', models.DateTimeField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Vessel_Identifier',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('column_name', models.CharField(max_length=200)),
        #         ('values_list', django.contrib.postgres.fields.jsonb.JSONField()),
        #     ],
        # ),
        # migrations.RemoveField(
        #     model_name='dataset',
        #     name='observation',
        # ),
        # migrations.RemoveField(
        #     model_name='dataset',
        #     name='spatiaNorth',
        # ),
        # migrations.AddField(
        #     model_name='dataset',
        #     name='hascoverage_img',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='dataset',
        #     name='observations',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='dataset',
        #     name='spatialNorth',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='vessel_identifier',
        #     name='dataset',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_identifiers', to='aggregator.Dataset'),
        # ),
        # migrations.AddField(
        #     model_name='datasetaccessrequest',
        #     name='resource',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='aggregator.Dataset'),
        # ),
        # migrations.AddField(
        #     model_name='datasetaccessrequest',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
