# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0035_merge_20190219_1007'),
        ('aggregator', '0038_auto_20190227_1554'),
    ]

    operations = [
    ]
