# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0039_merge_20190316_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datasetaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 12, 58, 43, 390000)),
        ),
    ]
