# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_builder', '0003_auto_20180513_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardaccess',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_builder.Dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='access_list',
            field=models.ManyToManyField(through='dashboard_builder.DashboardAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
