# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_builder', '0003_auto_20180513_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.CharField(max_length=512),
        ),
    ]
