# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_builder', '0004_auto_20180914_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_builder.Dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dashboardaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
