# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0004_auto_20180914_2312'),
        ('dashboard_builder', '0004_auto_20180717_1607'),
    ]

    operations = [
    ]
