# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0006_dashboardaccessrequest_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardaccessrequest',
            name='is_open',
        ),
        migrations.AddField(
            model_name='dashboardaccessrequest',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='open', max_length=20),
        ),
    ]
