# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0007_auto_20190218_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 6, 12, 363000)),
        ),
        migrations.AlterField(
            model_name='dashboardaccessrequest',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='dashboard_builder.Dashboard'),
        ),
    ]
