# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0008_auto_20190221_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardaccessrequest',
            old_name='dashboard',
            new_name='resource',
        ),
        migrations.AlterField(
            model_name='dashboardaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 17, 57, 782000)),
        ),
    ]
