# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0009_auto_20190619_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='can_be_shared',
            field=models.BooleanField(default=False),
        ),
        # migrations.AlterField(
        #     model_name='dashboardaccessrequest',
        #     name='creation_date',
        #     field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 15, 25, 33, 584000)),
        # ),
    ]
