# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('dashboard_builder', '0010_auto_20190221_1716'),
        #('dashboard_builder', '0006_auto_20181009_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 15, 29, 19, 269319)),
        ),
    ]
