# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0011_auto_20190301_1529'),
#        ('dashboard_builder', '0007_merge_20181120_1538'),
    ]

    operations = [
    ]
