# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0012_merge_20190316_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 12, 58, 43, 802000)),
        ),
    ]
