# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_builder', '0013_auto_20190327_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='can_be_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dashboardaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 16, 27, 30, 106000)),
        ),
    ]
