# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnDemandRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('keywords_raw', models.TextField(blank=True)),
                ('pricing', models.CharField(choices=[('FREE', 'No reward'), ('FIXED', 'Fixed price'), ('TBD', 'Negotiable')], db_index=True, max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('closed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='on_demand.OnDemandReply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnDemandUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='on_demand.OnDemandRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ondemandreply',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='on_demand.OnDemandRequest'),
        ),
        migrations.AddField(
            model_name='ondemandreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ondemandupvote',
            unique_together=set([('user', 'request')]),
        ),
    ]
