# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on_demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondemandreply',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='on_demand.OnDemandRequest'),
            preserve_default=False,
        ),
    ]
