# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('on_demand', '0002_ondemandreply_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ondemandupvote',
            unique_together=set([('user', 'request')]),
        ),
    ]
