# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdo_profile', '0002_userprofile_business_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', ''), ('DATA_ANALYST', 'Data analyst'), ('BUSINESS_USER', 'Business user'), ('RESEARCHER', 'Researcher'), ('SERVICE_DEVELOPER', 'Service developer')], default='', max_length=32),
        ),
    ]
