# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplans',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 16, 34, 31, 780000)),
        ),
    ]
