# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 10:41
from __future__ import unicode_literals

from django.db import migrations

def update_services(apps, schema_editor):

    Service = apps.get_model('bdo_main_app', 'Service')
    clustering = Service.objects.get(pk=1)
    clustering.info = {u'extendable': True, u'arguments': [{u'type': u'QUERY', u'name': u'query', u'title': u'Query'}, {u'type': u'COLUMN', u'name': u'feat_1', u'title': u'Feature 1'}, {u'type': u'COLUMN', u'name': u'feat_2', u'title': u'Feature 2'}]}
    clustering.save()

    quantile_discr = Service.objects.get(pk=7)
    quantile_discr.info = {u'extendable': True, u'arguments': [{u'type': u'QUERY', u'name': u'query', u'title': u'Query'}, {u'type': u'COLUMN', u'name': u'feat_1', u'title': u'Feature 1'}]}
    quantile_discr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bdo_main_app', '0003_auto_20170918_1811'),
    ]

    operations = [
        migrations.RunPython(update_services),
    ]
